# Generated by Django 5.0.4 on 2025-06-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meallog',
            name='calories',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='meallog',
            name='carbs',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='meallog',
            name='fat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='meallog',
            name='protein',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='meallog',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='meallog',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
